#!/usr/bin/env bash
# Example workflow for the Reasoning Trace Visualizer
#
# This script shows the typical steps for using the extension.
# Run with: bash examples/workflow.sh

echo "=== Reasoning Trace Visualizer: Example Workflow ==="
echo ""
echo "The extension is loaded automatically when pi starts"
echo "in a project with .pi/settings.json containing:"
echo ""
echo '  { "extensions": ["./extensions/reasoning-trace-viz/extensions/index.ts"] }'
echo ""
echo "=== Step 1: Start pi ==="
echo "  pi"
echo ""
echo "  Footer will show: 🧠 0 traces"
echo ""
echo "=== Step 2: Ask a complex question ==="
echo "  'Explain the key differences between self-attention and cross-attention"
echo "   in transformer architectures, including when you'd use each one.'"
echo ""
echo "  The extension captures the thinking block automatically."
echo "  Footer updates to: 🧠 1 traces"
echo ""
echo "=== Step 3: View the trace ==="
echo "  /thinking-log"
echo ""
echo "=== Step 4: Ask another question with a different model ==="
echo "  /model  (switch to Claude or Gemini)"
echo "  'Same question: self-attention vs cross-attention.'"
echo ""
echo "=== Step 5: Compare the two models ==="
echo "  /thinking-compare deepseek claude"
echo ""
echo "=== Step 6: Generate a diagram ==="
echo "  /thinking-diagram"
echo ""
echo "=== Step 7: Export for your blog ==="
echo "  /thinking-export > my-research.md"
echo "  # or:"
echo "  /thinking-blog"
echo ""
echo "=== Step 8: Interactive viewer ==="
echo "  /thinking-viz"
echo "  (navigate with ↑↓, select with Enter, close with Esc)"
echo ""
echo "=== Step 9: Statistics ==="
echo "  /thinking-stats"
echo ""
echo "Done!"